# Generated by Django 6.0.3 on 2026-04-02 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couple_name', models.CharField(blank=True, max_length=255, null=True)),
                ('list_title', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.IntegerField(db_index=True, default=1)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('purchased', 'Comprado')], db_index=True, default='available', max_length=50)),
                ('reserved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gifts.couple')),
            ],
            options={
                'db_table': 'gifts',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['-created_at'], name='couples_created_0bcc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['user'], name='couples_user_id_e55d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['couple', 'status'], name='gifts_couple__ba9da8_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['-created_at'], name='gifts_created_77cc88_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['status'], name='gifts_status_ef9226_idx'),
        ),
    ]
