# Generated by Django 5.2.13 on 2026-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gift',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='image_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
