# Generated by Django 5.2.13 on 2026-04-13 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_remove_gift_image_url_gift_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='gifts.gift')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gift'], name='donations_gift_id_550374_idx'), models.Index(fields=['-created_at'], name='donations_created_95af24_idx')],
            },
        ),
    ]
