# Generated by Django 5.2.13 on 2026-04-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='image_mimetype',
        ),
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
