# Generated by Django 6.0.5 on 2026-05-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_remove_gift_image_data_remove_gift_image_mimetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='donation_options',
            field=models.JSONField(blank=True, default=list, help_text='Array com 3 valores de doação em centavos (ex: [50000, 100000, 150000])', null=True),
        ),
    ]
