# Generated by Django 6.0.5 on 2026-05-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_donation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='theme',
            field=models.CharField(blank=True, choices=[('rose', 'Rosa'), ('purple', 'Roxo'), ('blue', 'Azul'), ('emerald', 'Esmeralda'), ('amber', 'Âmbar'), ('orange', 'Laranja')], default='rose', max_length=20),
        ),
    ]
