// Mock data for development - remove when connecting to real backend

import { Couple, Gift } from '../types';

export const mockCouple: Couple = {
  id: '1',
  email: 'casal@email.com',
  coupleName: 'Iara & Ramon',
  listTitle: 'Chá de Panela da Iara e do Ramon',
  whatsapp: '5511999999999',
  pixKey: 'iara.ramon@email.com',
  qrCodeUrl: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockGifts: Gift[] = [
  {
    id: '1',
    coupleId: '1',
    title: 'Jogo de Panelas Antiaderente',
    description: 'Conjunto completo com 5 panelas antiaderentes de alta qualidade para o dia a dia.',
    price: 350.00,
    imageUrl: 'https://images.unsplash.com/photo-1584990347449-a6eb73a567f4?w=400&q=80',
    isSelected: false,
    selectedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    coupleId: '1',
    title: 'Liquidificador Premium',
    description: 'Liquidificador de alta potência com múltiplas velocidades.',
    price: 280.00,
    imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400&q=80',
    isSelected: false,
    selectedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    coupleId: '1',
    title: 'Jogo de Toalhas de Banho',
    description: 'Kit com 6 toalhas macias 100% algodão em tons neutros.',
    price: 180.00,
    imageUrl: 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=400&q=80',
    isSelected: true,
    selectedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    coupleId: '1',
    title: 'Cafeteira Elétrica',
    description: 'Cafeteira programável com jarra térmica para 12 xícaras.',
    price: 220.00,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80',
    isSelected: false,
    selectedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    coupleId: '1',
    title: 'Jogo de Cama Queen',
    description: 'Jogo de cama 400 fios com 4 peças em algodão egípcio.',
    price: 450.00,
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80',
    isSelected: false,
    selectedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    coupleId: '1',
    title: 'Aspirador de Pó Robô',
    description: 'Aspirador inteligente com mapeamento e controle por app.',
    price: 800.00,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    isSelected: false,
    selectedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];